apiVersion: v1
kind: Namespace
metadata:
  name: ping-workspace
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: govee-intent-config
  namespace: ping-workspace  # 可根据实际命名空间修改
data:
  AZURE_OPENAI_ENDPOINT: "https://ping-openai-eastus2.openai.azure.com/"
  AZURE_OPENAI_CHAT_DEPLOYMENT_VERSION: "2024-10-01-preview"
  AZURE_OPENAI_CHAT_DEPLOYMENT: "gpt-4o-mini"
---  
apiVersion: v1
kind: Secret
metadata:
  name: govee-intent-secret
  namespace: ping-workspace  # 根据实际命名空间调整
type: Opaque
data:
